# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://wilkins007.github.io/
date_format: "ordinal"
title: Wilkins bolg
subtitle: "The most difficult thing is the decision to act. And the rest is merely tenacity."
description: "钟伟建的个人博客"
keywords: Wilkins bolg,博客, Wilkins Zhong, zwjlogin, wilinks
favicon: /favicon.ico
timezone: Asia/GuangZhou
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Wilkins Zhong
organization: Sogou, Inc.
organization_url: https://www.sogou.com
location: Guangzhou, China
email: 505565086@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /command/
    label: 命令

  -
    href: /links/
    label: 友情链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: wilkins007.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: zwjlogin
douban_username: freedim
facebook_username: zwjlogin
weibo_username: zwjlogin
zhihu_username: zwjlogin
twitter_username: zwjlogin

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: wilkinszhong
disqus_username: zwjlogin
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [Java, C++, Python, Design Patterns]
skill_mobile_app_keywords: [Android, Reverse Engineering]
skill_windows_keywords: [Win32 SDK, DuiLib, WTL, COM, WinDbg]
